# Generated by Django 4.0.6 on 2022-08-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.FileField(upload_to='Medialar')),
                ('prisident', models.CharField(max_length=30)),
                ('yil', models.DateField(auto_now_add=True)),
                ('record_tr', models.PositiveSmallIntegerField()),
                ('record_ar', models.PositiveSmallIntegerField()),
                ('davlat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('davlat', models.CharField(max_length=50)),
                ('pazitsiya', models.CharField(max_length=50)),
                ('narx', models.PositiveSmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodbolapp.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_narx', models.PositiveSmallIntegerField()),
                ('narx', models.PositiveSmallIntegerField()),
                ('mavsum', models.CharField(max_length=50)),
                ('cl_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_from', to='Foodbolapp.club')),
                ('club_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodbolapp.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodbolapp.player')),
            ],
        ),
    ]
