# Generated by Django 4.0.6 on 2022-08-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodbolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='davlat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodbolapp.davlat'),
        ),
    ]
