# Generated by Django 4.0.6 on 2022-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodbolapp', '0002_davlat_alter_club_davlat'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='murabbiy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
