# Generated by Django 4.0.6 on 2022-08-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodbolapp', '0003_club_murabbiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='yil',
            field=models.DateField(null=True),
        ),
    ]
